[build]
rustc-wrapper = ".cache/tools/kache.exe"

[env]
KACHE_CONFIG = { value = ".kache.toml", relative = true, force = true }
KACHE_CACHE_DIR = { value = ".cache/kache", relative = true, force = true }
KACHE_RUNTIME_DIR = { value = ".cache/runtime", relative = true, force = true }
CARGO_INCREMENTAL = { value = "0", force = true }