export global IconMap {
    out property <image> action-back: @image-url("actions/back.svg");
    out property <image> action-forward: @image-url("actions/forward.svg");
    out property <image> action-up: @image-url("actions/up.svg");
    out property <image> action-refresh: @image-url("actions/refresh.svg");
    out property <image> action-sort: @image-url("actions/sort.svg");
    out property <image> action-view: @image-url("actions/view.svg");
    out property <image> action-group: @image-url("actions/group.svg");
    out property <image> action-columns: @image-url("actions/columns.svg");
    out property <image> action-check: @image-url("actions/check.svg");
    out property <image> action-close: @image-url("actions/close.svg");
    out property <image> action-close-hover: @image-url("actions/close-white.svg");
    out property <image> action-add: @image-url("actions/add.svg");
    out property <image> action-menu: @image-url("actions/menu.svg");
    out property <image> action-settings: @image-url("actions/settings.svg");
    out property <image> action-language: @image-url("actions/language.svg");
    out property <image> action-search-recursive: @image-url("actions/search-recursive.svg");
    out property <image> action-search-current: @image-url("actions/search-current.svg");

    out property <image> file-folder: @image-url("files/folder.svg");
    out property <image> file-document: @image-url("files/document.svg");
    out property <image> status-locked: @image-url("status/lock-closed.svg");

    out property <image> location-home: @image-url("locations/home.svg");
    out property <image> location-desktop: @image-url("locations/desktop.svg");
    out property <image> location-downloads: @image-url("locations/downloads.svg");
    out property <image> location-documents: @image-url("locations/documents.svg");
    out property <image> location-pictures: @image-url("locations/pictures.svg");
    out property <image> location-music: @image-url("locations/music.svg");
    out property <image> location-videos: @image-url("locations/video.svg");
    out property <image> location-drive: @image-url("locations/drive.svg");
}
